### ISSUE TITLE
Unable to install via `pip`

### ISSUE THREAD

**Issue by NVedsted** [newaetech/chipwhisperer-tvla#2]
I tried to add this project as a dependency to my project, but no packages are installed with it. This seems to be due to the use of `find_packages('cwtvla')` in `setup.py`. It seems removing the parameter to `find_packages` allows it to detect the `cwtvla`.

However, it is probably easier to just put `['cwtvla']` and avoid the call altogether. :)

This happened on Windows if it is a platform-specific issue. I have never touched package publishing in Python, so I don't feel confident making a PR.

**Comment by NVedsted** [comment]
A few packages such as `zarr` and `tqdm` are also missing from the setup.

**Comment by alex-dewar** [comment]
Yeah, this has been an issue for a while, just haven't had the chance to debug. 

Thanks for figuring out what the actual issue was on this - I should be able get this fixed up pretty quick now. Will close when the issue is fixed.

**Comment by alex-dewar** [comment]
Alright, I think I've got this fixed. Let me know if the new version on pypi works for you.

Thank you very much for your help!

**Comment by NVedsted** [comment]
Awesome! That seemed to do the trick. :) Albeit, you cannot import it without `chipwhisperer` being present as well, so perhaps it should be uncommented as a dependency for now.
```
>>> import cwtvla
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\venv\lib\site-packages\cwtvla\__init__.py", line 2, in <module>
    from .ktp import verify_AES, FixedVRandomKey, FixedVRandomText, SemiFixedVRandomText
  File "...\venv\lib\site-packages\cwtvla\ktp.py", line 1, in <module>
    from chipwhisperer.common.utils import util
ModuleNotFoundError: No module named 'chipwhisperer'
```

**Comment by alex-dewar** [comment]
Whoops, got that fixed now as well.
